### ISSUE TITLE
Support `display-fill-column-indicator`

### ISSUE THREAD

**Issue by jaym** [FrostyX/evil-set-option#8]
Thanks for the great package. I ran into some issues installing it. There is a dependency on [fill-column-indicator](https://github.com/alpaker/fill-column-indicator). This repo says to use `display-fill-column-indicator` which now comes with emacs. It would be nice if this package could use that if its available. Right now, it fails if it cant require fill-column-indicator.

**Comment by FrostyX** [comment]
Thank you for the report and kind words @jaym,
can you please try if PR #9 fixes the issue for you?

**Comment by jaym** [comment]
works great, thank you

**Comment by FrostyX** [comment]
Perfect!
By the way, by suggesting `display-fill-column-indicator-mode` you helped me fix #7 which bothered me lately.

Thank you :-)
